CREATE TABLE ANIMALES (
  ID_ANIMALES INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_ANIMALES),
  INDEX ANIMALES_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE APOLO_KDB (
  ID_APOLO_KDB INT NOT NULL,
  PRIMARY KEY(ID_APOLO_KDB)
);

CREATE TABLE ARN (
  ID_ARN INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_ARN),
  INDEX ARN_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE BACTERIANA (
  ID_BACTERIANA INT(1) NOT NULL,
  MICROBIOLOGIA_ID_MICROBIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_BACTERIANA),
  INDEX BACTERIANA_FKIndex1(MICROBIOLOGIA_ID_MICROBIOLOGIA)
);

CREATE TABLE BIOINFORMATICA (
  ID_BIOINFORMATICA INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK  VARCHAR(150) NULL,
  PRIMARY KEY(ID_BIOINFORMATICA),
  INDEX BIOINFORMATICA_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE BIOINFORMATICA_3 (
  ID_BIOINFORMATICA INT(1) NOT NULL,
  GENOMICA_ID_GENOMICA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_BIOINFORMATICA),
  INDEX BIOINFORMATICA_2_FKIndex1(GENOMICA_ID_GENOMICA)
);

CREATE TABLE BIOLOGIA (
  ID_BIOLOGIA INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_BIOLOGIA),
  INDEX BIOLOGIA_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE BIOMECANICA (
  ID_BIOMECANICA INT(1) NOT NULL,
  FISIOLOGIA_2_ID_FISIOLOGIA_2 INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_BIOMECANICA),
  INDEX BIOMECANICA_FKIndex1(FISIOLOGIA_2_ID_FISIOLOGIA_2)
);

CREATE TABLE BIOMEDICINA (
  ID_BIOMEDICINA INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_BIOMEDICINA),
  INDEX BIOMEDICINA_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE CARDIOVASCULAR (
  ID_CARDIOVASCULAR INT(1) NOT NULL,
  FISIOLOGIA_2_ID_FISIOLOGIA_2 INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_CARDIOVASCULAR),
  INDEX CARDIOVASCULAR_FKIndex1(FISIOLOGIA_2_ID_FISIOLOGIA_2)
);

CREATE TABLE CELULAR (
  ID_CELULAR INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_CELULAR),
  INDEX CELULAR_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE CELULAS (
  ID_CELULA INT(1) NOT NULL,
  ESPACIO_ID_ESPACIO INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_CELULA),
  INDEX CELULAS_FKIndex1(ESPACIO_ID_ESPACIO)
);

CREATE TABLE CIENCIA_ESPACIAL (
  ID_CIENCIA_ESPACIAL INT(1) NOT NULL,
  MISION_CIENCIA_MCE INT(1) NOT NULL,
  LINK  VARCHAR(150) NULL,
  PRIMARY KEY(ID_CIENCIA_ESPACIAL),
  INDEX CIENCIA_ESPACIAL_FKIndex1(MISION_CIENCIA_MCE)
);

CREATE TABLE EFECTOS_CUERPO (
  ID_EFECTOS_CUERPO INT(1) NOT NULL,
  SALUD_ID_SALUD INT(1) NOT NULL,
  LINK  VARCHAR(150) NULL,
  PRIMARY KEY(ID_EFECTOS_CUERPO),
  INDEX EFECTOS_CUERPO_FKIndex1(SALUD_ID_SALUD)
);

CREATE TABLE ENDOCRONOLOGIA (
  ID_ENDOCRONOLOGIA INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_ENDOCRONOLOGIA),
  INDEX ENDOCRONOLOGIA_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE ENFERMEDADES (
  ID_ENFERMEDAD INT(1) NOT NULL,
  SALUD_ID_SALUD INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_ENFERMEDAD),
  INDEX ENFERMEDADES_FKIndex1(SALUD_ID_SALUD)
);

CREATE TABLE ESPACIAL (
  ID_ESPACIAL INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_ESPACIAL),
  INDEX ESPACIAL_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE ESPACIAL_3 (
  ID_ESPACIAL INT(1) NOT NULL,
  MICROBIOLOGIA_ID_MICROBIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_ESPACIAL),
  INDEX ESPACIAL_2_FKIndex1(MICROBIOLOGIA_ID_MICROBIOLOGIA)
);

CREATE TABLE ESPACIO (
  ID_ESPACIO INT(1) NOT NULL,
  SALUD_ID_SALUD INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_ESPACIO),
  INDEX ESPACIO_FKIndex1(SALUD_ID_SALUD)
);

CREATE TABLE ETICA (
  ID_ETICA INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_ETICA),
  INDEX ETICA_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE EXPERIMENTAL (
  ID_EXPERIMENTAL INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_EXPERIMENTAL),
  INDEX EXPERIMENTAL_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE EXTREMOFILOS (
  ID_EXTREMOFILOS INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_EXTREMOFILOS),
  INDEX EXTREMOFILOS_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE FILOSOFIA_CIENCIA (
  ID_FILOSOFIA_CIENCIA INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_FILOSOFIA_CIENCIA),
  INDEX FILOSOFIA_CIENCIA_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE FILOSOFIA_VEGETAL (
  ID_FILOSOFIA_VEGETAL INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_FILOSOFIA_VEGETAL),
  INDEX FILOSOFIA_VEGETAL_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE FISIOLOGIA (
  ID_FISIOLOGIA INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_FISIOLOGIA),
  INDEX FISIOLOGIA_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE FISIOLOGIA_2 (
  ID_FISIOLOGIA_2 INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_FISIOLOGIA_2),
  INDEX FISIOLOGIA_2_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE FISIOLOGIA_EQUILIBRIO (
  ID_FISIOLOGIA_EQUILIBRIO INT(1) NOT NULL,
  NEUROCIENCIA_ID_NEUROCIENCIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_FISIOLOGIA_EQUILIBRIO),
  INDEX FISIOLOGIA_EQUILIBRIO_FKIndex1(NEUROCIENCIA_ID_NEUROCIENCIA)
);

CREATE TABLE FISIOLOGIA_MUSCULOESQUELETICA (
  ID_FISIOLOGIA_MUSCULOESQUELETICA INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_FISIOLOGIA_MUSCULOESQUELETICA),
  INDEX FISIOLOGIA_MUSCULOESQUELETICA_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE GENOMICA (
  ID_GENOMICA INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_GENOMICA),
  INDEX GENOMICA_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE INMUNOLOGIA_ESPACIAL (
  ID_INMUNOLOGIA_ESPACIAL INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_INMUNOLOGIA_ESPACIAL),
  INDEX INMUNOLOGIA_ESPACIAL_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE MEDICINA_ESPACIAL (
  ID_MEDICINA_ESPACIAL INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_MEDICINA_ESPACIAL),
  INDEX MEDICINA_ESPACIAL_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE MEDICINA_ESPACIAL_2 (
  ID_MEDICINA_ESPACIAL_2 INT(1) NOT NULL,
  FISIOLOGIA_2_ID_FISIOLOGIA_2 INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_MEDICINA_ESPACIAL_2),
  INDEX MEDICINA_ESPACIAL_2_FKIndex1(FISIOLOGIA_2_ID_FISIOLOGIA_2)
);

CREATE TABLE MEDICINA_ESPACIAL_3 (
  ID_MEDICINA_ESPACIAL_3 INT(1) NOT NULL,
  NEUROCIENCIA_ID_NEUROCIENCIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_MEDICINA_ESPACIAL_3),
  INDEX MEDICINA_ESPACIAL_3_FKIndex1(NEUROCIENCIA_ID_NEUROCIENCIA)
);

CREATE TABLE MICROBIOLOGIA (
  ID_MICROBIOLOGIA INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_MICROBIOLOGIA),
  INDEX MICROBIOLOGIA_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE MICROGRAVEDAD (
  ID_MICROGRAVEDAD INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_MICROGRAVEDAD),
  INDEX MICROGRAVEDAD_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE MISION (
  ID_MISION INT(1) NOT NULL,
  MISION_CIENCIA_MCE INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_MISION),
  INDEX MISION_FKIndex1(MISION_CIENCIA_MCE)
);

CREATE TABLE MISION_CIENCIA (
  MCE INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(MCE),
  INDEX MISION_CIENCIA_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE MOLECULAR_VEGETAL (
  ID_MOLECULAR_VEGETAL INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_MOLECULAR_VEGETAL),
  INDEX MOLECULAR_VEGETAL_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE NEUROBIOLOGIA_ESPACIAL (
  ID_NEUROBIOLOGIA_ESPACIAL INT(1) NOT NULL,
  NEUROCIENCIA_ID_NEUROCIENCIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_NEUROBIOLOGIA_ESPACIAL),
  INDEX NEUROBIOLOGIA_ESPACIAL_FKIndex1(NEUROCIENCIA_ID_NEUROCIENCIA)
);

CREATE TABLE NEUROCIENCIA (
  ID_NEUROCIENCIA INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_NEUROCIENCIA),
  INDEX NEUROCIENCIA_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE OSEA (
  ID_OSEA INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_OSEA),
  INDEX OSEA_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE RADIACION (
  ID_RADIACION INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_RADIACION),
  INDEX RADIACION_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE RADIOLOGIA (
  ID_RADIOLOGIA INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_RADIOLOGIA),
  INDEX RADIOLOGIA_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE SALUD (
  ID_SALUD INT(1) NOT NULL,
  APOLO_KDB_ID_APOLO_KDB INT NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_SALUD),
  INDEX SALUD_FKIndex1(APOLO_KDB_ID_APOLO_KDB)
);

CREATE TABLE SENSORIAL (
  ID_SENSORIAL INT(1) NOT NULL,
  NEUROCIENCIA_ID_NEUROCIENCIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_SENSORIAL),
  INDEX SENSORIAL_FKIndex1(NEUROCIENCIA_ID_NEUROCIENCIA)
);

CREATE TABLE Staphylococcus (
  ID_Staphylococcus INT(1) NOT NULL,
  MICROBIOLOGIA_ID_MICROBIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_Staphylococcus),
  INDEX Staphylococcus_FKIndex1(MICROBIOLOGIA_ID_MICROBIOLOGIA)
);

CREATE TABLE VEGETAL (
  ID_VEGETAL INT(1) NOT NULL,
  BIOLOGIA_ID_BIOLOGIA INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_VEGETAL),
  INDEX VEGETAL_FKIndex1(BIOLOGIA_ID_BIOLOGIA)
);

CREATE TABLE VIROLOGIA (
  ID_VIROLOGIA INT(1) NOT NULL,
  SALUD_ID_SALUD INT(1) NOT NULL,
  LINK VARCHAR(150) NULL,
  PRIMARY KEY(ID_VIROLOGIA),
  INDEX VIROLOGIA_FKIndex1(SALUD_ID_SALUD)
);

